### ISSUE TITLE
Did you want help to create bioconda package

### ISSUE THREAD

**Issue by natir** [oschwengers/referenceseeker#1]
Hello @oschwengers,

I currently use referenceseeker and I plan to create a referenceseeker bioconda package. For this, I create the medusa bioconda package.

I see in your recent commit you plan to create a bioconda package for referenceseeker did you want some help?

**Comment by oschwengers** [comment]
Hello @natir , wonderfull!
I just decided yesterday to drop Docker and build a BioConda image. 
As there was no MeDuSa recipe, I decided to drop the scaffolding feature in order to speedup the BioConda migration. 
If you could add MeDuSa to BioConda, I could add this feature back to RS if this is desired.
So any help with BioConda/MeDuSa is indeed highly welcome!

**Comment by oschwengers** [comment]
@natir I forgot this is my current PR: https://github.com/bioconda/bioconda-recipes/pull/19343

**Comment by natir** [comment]
MeDuSa are currently available in bioconda but I miss python package dependency, so I make another pull request and I hope it will be merge near in future bioconda/bioconda-recipes#19341. So I think you can readd the scaffolding feature in referenceseeker.

I am gooing to review your bioconda PR.
