### ISSUE TITLE
Empty matrix

### ISSUE THREAD

**Issue by theo-llewellyn** [oschwengers/referenceseeker#3]
Hello,

I'm trying to run referenceseeker and it seems to run fine without any error messages but the output is just an empty matrix like this (ive removed the full path names):

ReferenceSeeker v1.4
Options, parameters and arguments:
	use bundled binaries: False
	db path: home/fungi
	genome path: final.contigs.fa
	tmp path:
	unfiltered: False
	bidirectional: False
	ANI: 0.95
	conserved DNA: 0.69
	# CRG: 100
	# threads: 56

Estimate genome distances...
	screened 0 potential reference genome(s)

Compute ANIs...

#ID	Mash Distance	ANI	Con. DNA	Taxonomy ID	Assembly Status	Organism

Any ideas what could be the problem? It seems to be screening 0 genomes. I have looked manually at the database folder and the sequences are all there. Here's my input code:

`referenceseeker home/fungi final.contigs.fa --verbose`

Thanks for your help.

Best wishes,
Theo

**Comment by oschwengers** [comment]
Hi @theo-llewellyn , thanks for your report.
> screened 0 potential reference genome(s)

This means that the `kmer`-lookup step could not find any "close-enough" reference candidates (default mash distance = 0.1).

Unfortunately, fungi are not yet covered very well by the databases. So, could it simply be the case, that there is no closely related reference genome in the database for your query genome?

You could decrease the `kmer`-lookup similarity threshold and skip any `ANI` and `conserved DNA` thresholds. This will allow the report of more distant reference genomes.
In order to to so, just try the `--unfiltered` option which I included for these situations. For genomes with a large number of reference genomes (e.g. Ecoli) this results in very long runtimes. But in your case you could find some more distant reference(s).

**Comment by theo-llewellyn** [comment]
Hi Oliver,

That makes sense, the group of fungi that I'm studying currently have no reference genomes. Ill retry with the --unfiltered option and see what happens.

Thanks for your help. Great programme!!

Theo

**Comment by oschwengers** [comment]
Hi Theo ( @theo-llewellyn ),
thanks to some great comments during the ongoing JOSS review I implemented a new feature which allows for the creation of custom databases with unpublished genomes as well as the addition of such to the existing public databases. If you have one or more private / unpublished (reference) genome(s), you could try to setup a new db or add them to the public fungi db If this makes sense in your case.
If you need any guidance or face any issues, please don't hesitate to reach out!
Best regards

**Comment by theo-llewellyn** [comment]
Hi Oliver,
Thanks for that information. That's really helpful and I'll definitely try creating a custom database. I'll let you know if I have any issues.
Best
Theo

**Comment by oschwengers** [comment]
Hi @theo-llewellyn , I just saw that this is still open. I hope the new db setup feature works out for you?

I'll close this for now - just in case you have any issues or questions, please feel free to reopen this or create a new one!

Best regards!
