### ISSUE TITLE
Test suite or instructions

### ISSUE THREAD

**Issue by standage** [oschwengers/referenceseeker#4]
Great package, thanks for making this available!

Surely you have tested ReferenceSeeker extensively to make sure it performs as expected on numerous inputs. However, unless I'm mistaken, the documentation doesn't include any instructions for running an automated test suite or commands to execute to ensure the software is installed correctly.

Bundling entire bacterial/viral/fungal/etc. components of RefSeq with the software to support an automated test suite isn't feasible—it would require an incredible amount of storage for an otherwise lightweight package. However, one possible approach would be to construct a smaller mock database with a small number of entries that could be more easily bundled with ReferenceSeeker.

At the very least, beginners would benefit from 1 or 2 test examples that very clearly demonstrate:

- how to download the input data
- how to run the test
- what the expected output should be

**Comment by oschwengers** [comment]
Hi @standage , thanks a lot for this!
You're absolutely right, so far there hasn't been any test functionality mainly due to the large databases as you've already pinpointed it.

I therefore created a tiny mock db comprising only 4 *Salmonella spp* genomes as well as a test query genome from SRA and added this to a new `tests` directory.

Accordingly, I added a short `Test` subsection to the `Installation` section of the readme. 

As for now, I'd rather stick to this simple test case not to flood the readme too much.
Would you consider this as sufficient and comprehensible or would you like to see even more test cases?

**Comment by standage** [comment]
Looks good to me. Thanks!
